apiVersion: apps/v1
kind: Deployment
metadata:
  name: whacdamole-operator
  labels:
    app: whacdamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whacdamole
  template:
    metadata:
      labels:
        app: whacdamole
    spec:
      serviceAccountName: whacdamole-operator
      containers:
        - name: whacdamole
          image: whacdamole.registry/whacdamole:0.0.1
          args: ["gitops"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
