apiVersion: v1
kind: ServiceAccount
metadata:
  name: whacdamole-operator
  labels:
    app: whacdamole
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: whacdamole-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "events"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["whackdamole.github.com"]
    resources: ["whacdemoles"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: whacdamole-operator
subjects:
  - kind: ServiceAccount
    name: whacdamole-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: whacdamole-operator
  apiGroup: rbac.authorization.k8s.io
