---
apiVersion: whackdamole.github.com/v1beta
kind: Whacdamole
metadata:
  name: my-project
spec:
  name: MyProject
  version: "1.0.0"
  gitRepo: https://github.com/example/my-project.git
  branchToWatch: main
  localEnvironment:
    enableLocalKubernetes: true
    enableLocalKubernetesTraefik: true
    enableLocalDockerRegistry: true
    localDockerRegistryPort: 5000
    localDockerRegistries:
      - "http://my-registry.local:5000"
    localDockerRegistriesFile:
      configs:
        "registry.example.com:5000":
          auth:
            username: xxxxxx
            password: xxxxxx
          tls:
            cert_file: # path to the cert file used in the registry
            key_file:  # path to the key file used in the registry
            ca_file:   # path to the ca file used in the registry
      mirrors:
        registry.example.com:
          endpoint:
            - "https://registry.example.com:5000"
          rewrites:
            "^rancher/(.*)": "mirrorproject/rancher-images/$1"

    localKubernetesAgentCount: 1
    localKubernetesPorts:
      - 1234:1234
      - 80:80
      - 443:443
    kubeconfig: "/home/user/.kube/config"
  dockerImages:
    - name: backend
      tags:
        - "0.0.1"
        - "latest"
      registry: docker.io/myrepo
      directory: ./services/backend
    - name: frontend
      tags:
        - "0.0.1"
        - "latest"
      registry: docker.io/myrepo
      directory: ./services/frontend
  helmDeployments:
    - gitRepo: https://github.com/example/helm-charts.git
      branchToWatch: release
      releasePath: charts/mychart
      releaseVersion: 1.0.0
      helmRepo: helm-repo
      helmRepoPath: https://repo/dir/
      values: |
        replicaCount: 2
        image:
          repository: myrepo/backend
          tag: "0.0.1"
      overrides:
        environment: production
        debug: "false"
  kustomizeDeployments:
    - gitRepo: https://github.com/example/kustomize-configs.git
      branchToWatch: develop
      kustomizePath: overlays/production
